### ISSUE TITLE
Not showing client count/list

### ISSUE THREAD

**Issue by zdziebek77xd** [P0cL4bs/WiFi-Pumpkin#153]
Not showing client count/list

and cannot sniff https... 
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 1366, in Start_PumpAP
    thread.start()
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 265, in start
    config = proxy.ProxyConfig(port=8080,mode='transparent')
TypeError: __init__() got an unexpected keyword argument 'mode'
killing all threads...

* Card wireless adapters name (please check if support AP/mode): Supported ath9k ar928X
* Version used tool: 0.8.4
* Virtual Machine (yes or no and which): NO
* Operating System and version: LMDE2

**Comment by mh4x0f** [comment]
I think that your version mitmproxy lib is not 0.17 ,This an #69 were the same.
