### ISSUE TITLE
developer why close my treatment!

### ISSUE THREAD

**Issue by rdbox** [P0cL4bs/WiFi-Pumpkin#398]
your wiki did not help me Are you a developer? why do not you help me?
You just close my appeal is not respect.

If you are sure that WiFi-Pumpkin is stable and working, show it in your complete instructions.

 

Your approach to solving problems offends me, why should I do this?
I need help, I want to run WiFi-Pumpkin that would work stably

**Comment by mh4x0f** [comment]
look, ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY

**Comment by mh4x0f** [comment]
@rdbox this is the bad part of creating opensource projects, most users do not even want to search for the error in google for what is happening, when it does not report some that has already been reported, there are still those who know absolutely nothing and want me to explain how things work.
